import os
import json
import shutil
import logging
import subprocess
import time
import socket
from pathlib import Path
from playwright_stealth import Stealth
from playwright.async_api import async_playwright, BrowserContext, Page, Playwright
from .profiles import profile_registry

logger = logging.getLogger(__name__)

class BrowserManager:
    _instance = None
    _playwright: Playwright = None
    _contexts: dict[str, BrowserContext] = {}

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(BrowserManager, cls).__new__(cls)
        return cls._instance

    @classmethod
    async def get_instance(cls):
        if cls._instance is None:
            cls._instance = BrowserManager()
        return cls._instance

    def _hex_to_skcolor(self, hex_color: str) -> int:
        """Converts hex color to Chrome's signed int SkColor format."""
        try:
            hex_color = hex_color.lstrip('#')
            # Add Alpha (FF) if not present
            if len(hex_color) == 6:
                hex_color = 'FF' + hex_color
            
            # Big endian hex to int
            val = int(hex_color, 16)
            # Convert to signed 32-bit int if needed
            if val > 0x7FFFFFFF:
                val -= 0x100000000
            return val
        except:
            return -13158601 # Default reddish color

    def _decorate_profile(self, user_data_dir: str, name: str, color: str):
        """Sets profile name and theme color in Chrome's preference files."""
        try:
            color_int = self._hex_to_skcolor(color)
            
            # 1. Update Preferences
            prefs_path = os.path.join(user_data_dir, "Default", "Preferences")
            os.makedirs(os.path.dirname(prefs_path), exist_ok=True)
            
            prefs = {}
            if os.path.exists(prefs_path):
                with open(prefs_path, "r", encoding="utf-8") as f:
                    prefs = json.load(f)
            
            # Update Profile Name
            if "profile" not in prefs: prefs["profile"] = {}
            prefs["profile"]["name"] = name
            
            # Update Theme Color
            if "autogenerated" not in prefs: prefs["autogenerated"] = {}
            if "theme" not in prefs["autogenerated"]: prefs["autogenerated"]["theme"] = {}
            prefs["autogenerated"]["theme"]["color"] = color_int
            
            if "browser" not in prefs: prefs["browser"] = {}
            if "theme" not in prefs["browser"]: prefs["browser"]["theme"] = {}
            prefs["browser"]["theme"]["user_color2"] = color_int
            
            with open(prefs_path, "w", encoding="utf-8") as f:
                json.dump(prefs, f, indent=4)

            # 2. Update Local State (Profile cache)
            local_state_path = os.path.join(user_data_dir, "Local State")
            local_state = {}
            if os.path.exists(local_state_path):
                with open(local_state_path, "r", encoding="utf-8") as f:
                    local_state = json.load(f)
            
            if "profile" not in local_state: local_state["profile"] = {}
            if "info_cache" not in local_state["profile"]: local_state["profile"]["info_cache"] = {}
            if "Default" not in local_state["profile"]["info_cache"]: local_state["profile"]["info_cache"]["Default"] = {}
            
            local_state["profile"]["info_cache"]["Default"]["name"] = name
            local_state["profile"]["info_cache"]["Default"]["profile_color_seed"] = color_int
            
            with open(local_state_path, "w", encoding="utf-8") as f:
                json.dump(local_state, f, indent=4)
                
            logger.info(f"Profile '{name}' decorated with color {color}.")
        except Exception as e:
            logger.error(f"Failed to decorate profile: {e}")

    def _get_chrome_path(self):
        """Locates Chrome executable."""
        path = os.getenv("CHROME_EXECUTABLE_PATH")
        if path and os.path.exists(path):
            return path

        paths = [
            r"C:\Program Files\Google\Chrome\Application\chrome.exe",
            r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
            os.path.expandvars(r"%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe"),
        ]
        
        for p in paths:
            if os.path.exists(p):
                return p
        return shutil.which("chrome") or shutil.which("google-chrome")

    async def get_context(self, profile_name: str = "default") -> BrowserContext:
        """Starts playwright and returns a persistent context for the specified profile."""
        if profile_name in self._contexts:
            return self._contexts[profile_name]

        if not self._playwright:
            self._playwright = await async_playwright().start()

        profile = profile_registry.get_profile(profile_name)
        if not profile:
            profile = profile_registry.create_profile(profile_name)

        user_data_dir = profile["user_data_dir"]
        os.makedirs(user_data_dir, exist_ok=True)

        # Apply identity (Xbot/Profile Name)
        self._decorate_profile(user_data_dir, profile_name.capitalize(), profile["color"])

        chrome_path = self._get_chrome_path()
        headless = os.getenv("BROWSER_HEADLESS", "False").lower() == "true"

        # ADVANCED STEALTH ARGUMENTS
        args = [
            f"--remote-debugging-port={profile['cdp_port']}",
            "--disable-blink-features=AutomationControlled",
            "--no-first-run",
            "--no-default-browser-check",
            "--disable-infobars",
            "--disable-sync",
            "--disable-background-networking",
            "--disable-features=Translate,MediaRouter",
            "--password-store=basic",
            "--window-size=1920,1080"
        ]

        # NOTE: WE REMOVE --no-sandbox to avoid Google detection and banners
        
        launch_kwargs = {
            "user_data_dir": user_data_dir,
            "headless": headless,
            "args": args,
            "ignore_default_args": ["--enable-automation", "--no-sandbox"] 
        }

        if chrome_path:
            launch_kwargs["executable_path"] = chrome_path

        try:
            context = await self._playwright.chromium.launch_persistent_context(**launch_kwargs)
            self._contexts[profile_name] = context
            return context
        except Exception as e:
            logger.error(f"Failed to launch browser context for profile '{profile_name}': {e}")
            raise

    async def get_page(self, profile_name: str = "default") -> Page:
        """Returns the current page or creates a new one for the profile."""
        ctx = await self.get_context(profile_name)
        stealth = Stealth()
        
        if not ctx.pages:
            page = await ctx.new_page()
        else:
            page = ctx.pages[0]
            
        await stealth.apply_stealth_async(page)
        return page

    async def close(self, profile_name: str = None):
        """Closes a specific profile context or all of them."""
        if profile_name:
            if profile_name in self._contexts:
                await self._contexts[profile_name].close()
                del self._contexts[profile_name]
        else:
            for name in list(self._contexts.keys()):
                await self._contexts[name].close()
                del self._contexts[name]
                
            if self._playwright:
                await self._playwright.stop()
                self._playwright = None

browser_manager = BrowserManager()
